modLoader="javafml"
loaderVersion="[39,)"
license="GPLv3"

[[mods]]
modId="soliddmod"
version="1.2.0"
displayName="Solidd Steel"
logoFile="logo.png"
authors="JSolidd"
description='''A simple mod giving you an upgrade for iron. When an iron tool is upgraded to Solidd Steel, it is given a fair increase in durability and in some cases a slight effeciency bonus. Upgrade your armor for durability and a small armor toughness bonus.'''

[[dependencies.soliddmod]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soliddmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
